embeddings:
  model: "gemini-embedding-001"
  dimension: 3072
  model_provider: "google"

ingestion:
  entity_extraction: 
    model: "gemini-2.5-flash-lite"
    temperature: 0.2
    thinking_budget: 0
    model_provider: "google"
  summary_generation: 
    model: "gemini-2.5-flash-lite"
    temperature: 0.2
    thinking_budget: 0
    model_provider: "google"
  metadata_extraction: 
    model: "gemini-2.5-flash-lite"
    temperature: 0.2
    thinking_budget: 0
    model_provider: "google"

main:
  drafting_graph: 
    model: "gemini-2.5-flash-lite"
    temperature: 0.2
    thinking_budget: 0
    model_provider: "google"
    # Example: per-node configuration - uncomment to enable different LLMs per node
    nodes:
    #   fact_analyzer_node:
    #     model: "gemini-2.5-flash-lite"
    #     temperature: 0.1
    #     model_provider: "google"
    #   strategy_developer_node:
    #     model: "gpt-4o"
    #     temperature: 0.3
    #     model_provider: "openai"
      final_drafter_node:
        model: "gpt-5-mini"  # Use stronger model for critical assessment
        temperature: 0.5
        reasoning:
          effort: low
        model_provider: "openai"
  research_graph: 
    model: "gemini-2.5-flash-lite"
    temperature: 0.2
    thinking_budget: 0
    model_provider: "google"
    # Example: per-node configuration for research workflow
    # nodes:
    #   query_analyzer_node:
    #     model: "gpt-4o"
    #     temperature: 0.1
    #     model_provider: "openai"
    #   refine_analyzer_node:
    #     model: "gemini-2.5-flash-lite"
    #     temperature: 0.3
    #     model_provider: "google"
  counterargument_graph: 
    model: "gemini-2.5-flash-lite"
    temperature: 0.2
    thinking_budget: 0
    model_provider: "google"
    nodes:
    #   vulnerability_analysis_node:
    #     model: "gemini-2.5-flash-lite"  # Creative thinking for finding vulnerabilities
    #     temperature: 0.3
    #     model_provider: "google"
      challenge_identifier_node:
        model: "gpt-5-mini"  # Strong reasoning for identifying challenges
        temperature: 0.2
        reasoning:
          effort: minimal
        # thinking_budget: 200
        model_provider: "openai"
      counterargument_developer_node:
        model: "gpt-5-mini"  # Strong reasoning for developing arguments
        temperature: 0.2
        reasoning:
          effort: minimal
        # thinking_budget: 200
        model_provider: "openai"
      rebuttal_generator_node:
        model: "gpt-5-mini"  # Strong reasoning for rebuttals
        # thinking_budget: 200
        temperature: 0.2
        reasoning:
          effort: minimal
        model_provider: "openai"
  research_agent:
    model: "gemini-2.5-flash"
    temperature: 0.2
    thinking_budget: 128
    model_provider: "google"