export default {
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1a25ec0b": [() => import(/* webpackChunkName: "1a25ec0b" */ "@site/docs/features.md"), "@site/docs/features.md", require.resolveWeak("@site/docs/features.md")],
  "1db65d89": [() => import(/* webpackChunkName: "1db65d89" */ "@site/docs/user-guide.md"), "@site/docs/user-guide.md", require.resolveWeak("@site/docs/user-guide.md")],
  "1df93b7f": [() => import(/* webpackChunkName: "1df93b7f" */ "@site/src/pages/index.tsx"), "@site/src/pages/index.tsx", require.resolveWeak("@site/src/pages/index.tsx")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "6d29f0c5": [() => import(/* webpackChunkName: "6d29f0c5" */ "/Users/chanmalichan/Downloads/forecite/docusaurus/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json"), "/Users/chanmalichan/Downloads/forecite/docusaurus/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json", require.resolveWeak("/Users/chanmalichan/Downloads/forecite/docusaurus/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json")],
  "935f2afb": [() => import(/* webpackChunkName: "935f2afb" */ "~docs/default/version-current-metadata-prop-751.json"), "~docs/default/version-current-metadata-prop-751.json", require.resolveWeak("~docs/default/version-current-metadata-prop-751.json")],
  "9484d6bb": [() => import(/* webpackChunkName: "9484d6bb" */ "/Users/chanmalichan/Downloads/forecite/docusaurus/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json"), "/Users/chanmalichan/Downloads/forecite/docusaurus/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json", require.resolveWeak("/Users/chanmalichan/Downloads/forecite/docusaurus/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json")],
  "a09c2993": [() => import(/* webpackChunkName: "a09c2993" */ "@site/docs/introduction.md"), "@site/docs/introduction.md", require.resolveWeak("@site/docs/introduction.md")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],};
